version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes: 
      - .:/usr/src/app
    ports:
      - ${APP_PORT}:3000
    links:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
